### ISSUE TITLE
[request] Virtual Keyboard Option

### ISSUE THREAD

**Issue by M0BI0S** [moonlight-stream/moonlight-ios#122]
Hello,
I have been testing the moonlight app again on my iPad Air 2.

What came to my mind while testing, was the absence of the ability to use a keyboard, or I could not find it.

i.e. when I play elite:dangerous with the Steelseries Stratus XL, which works fine, I cannot enter any words in the provided spaces, in this case star-systems to search for, as there is no keyboard.
I have tried to connect my anker bluetooth keyboard. It connected succesfully along side the controller. But the keyboard strokes are not passed through the game.

I would think it would be nice to have the option to display a virtual keyboard on screen, maybe via a little corner button. 

What do you think?

**Comment by dwaxemberg** [comment]
This is something that I would like to add soon. Thanks for the feedback.

**Comment by firestorm185** [comment]
Yeah, that would be great for games like Hawken where you have to log in
first.

On Tue, Jun 2, 2015 at 11:03 PM, Diego Waxemberg <notifications@github.com>
wrote:

> This is something that I would like to add soon. Thanks for the feedback.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moonlight-stream/moonlight-ios/issues/122#issuecomment-108171892>
> .
>



-- 
Robbie Anthony Cartwright
firestorm185@gmail.com
Sonic Artist Expert. ;P

**Comment by Lucleonhart** [comment]
Any news here? There is a game-blocking password entry problem with FFXIV right now. ^_^
Awesome app by the way!

**Comment by Purduecoz** [comment]
Does the version of Moonlight for iOS that's in the App Store have virtual keyboard support?  The docs made it seem as if a triple tap activated this, yet it doesn't seem to work. Perhaps it's still an Android only feature?

**Comment by schmurtzm** [comment]
+1
It could be usefull to make login on steam easily or search a game in windows start menu  ;)

**Comment by Ekagrah** [comment]
+1 
Love this, just wish I could use the virtual keyboard on my iPad Pro to sign into games when needed.

**Comment by AJBats** [comment]
I would love this feature! I've got a keyboard on my IPad Pro and it currently does not map to the host computer. I would love it if it worked.

**Comment by relink2013** [comment]
Don’t mean to bring this back from the dead, but this is most certainly a needed feature. Pretty much the only game I stream is FFXIV, and while the launcher has its own on screen keyboard for putting in your password, you still can’t chat with anyone in game.

**Comment by AJBats** [comment]
> Don’t mean to bring this back from the dead, but this is most certainly a needed feature. 

I'm so glad someone else is holding out for this feature! I'd like to echo again I'd still love to see this feature added. I've had to come up with a crazy workaround that works OKish, but Id rather if it was built into the software.

**Comment by lamiska** [comment]
+1, I use wake on lan and keyboard is needed for windows login prompt

@AJBats - what kind of workaround do you use?

**Comment by AJBats** [comment]
@lamiska What I settled on was using a long USB extension cable and a bluetooth dongle to strategically place the bluetooth dongle in a place that can reach most of the rooms in my house. I then use a compact bluetooth keyboard that I carry around with my iPad. I had to experiment with a few different dongles, and some have further reach than others, but even the best ones have a shorter range than my 5g router, and therefore, the range of moonlight streaming.

I use the same trick when playing PC games that make use of the full XInput controller layout. Ios controllers are a few buttons short of the full compliment which can make some games awkward to play. I found that the Xbox one dongle has pretty good signal strength and I plug it in along side my bluetooth dongle. Though they now have xbone controllers with BT support, so perhaps that is simpler?

Extreme case: When I want to play on my backporch, I use virtual here USB app on my phone, and plug devices into my phone to send the USB signal over the stronger 5g wifi connection. But there's a lot of sticking points with this setup as the number of devices my phone can handle is limited, plus it drains the battery fast, and you have to fidget with it a bit on the PC side before it'll recognize the devices through my phone. It's so much rigmarole that I actually have given up doing this.

All the craziness I mentioned above would be eliminated if I could simply use the built in keyboard (or a locally paired BT keyboard, or apple smart keyboard). Even more if I could pair a controller with the full XInput compliment of buttons on ios. If I had those two things I could just grab my ipad and a controller and go wherever my 5g reached and have full access to my PC. I've come so close to simply buying an android tablet or nvidia shield since it can deliver on this. But I just love my iPad Pro big screen so much. 

In related news the steam app is going to support streaming soon, and depending what features that has this discussion might become moot!

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-ios/commit/76ab786e94b6949729b51043409660a102869543

**Comment by AJBats** [comment]
I'm utterly speechless. This is a feature years in anticipation. When can we expect it on the app store build?

**Comment by tatabax** [comment]
Is this feature added yet?

**Comment by cgutman** [comment]
Yes, 3 finger tap to toggle
