### ISSUE TITLE
"Connection failed: failed to launch app"

### ISSUE THREAD

**Issue by benjabones** [moonlight-stream/moonlight-ios#134]
It looks like im succesfully paired, but when i go to launch a game, my nvidia machine blackscreens breifly and i get the above error on moonlight on my ipad?

**Comment by onzyone** [comment]
I have seen something like this too, but the game lunches on my pc, and my ipad screen stays black

**Comment by Kaeltis** [comment]
You might want to try the moonlight-pc version on a different machine to know if the issue is related to moonlight-ios or if it's an incompatibility of GameStream on your machine.
There are many threads in the nvidia forums referring to the problems you described, some are caused by driver incompatibilities.

**Comment by benjabones** [comment]
strangely, this issue appears to have mysteriously cleared up? its working beautifully now!

**Comment by SireNightFire** [comment]
Im getting this issue
my PC is able to stream games however trying to use moonlight on my Iphone 6 iOS 8.1 device it just hangs on Starting App when i select a game then says "Connection failed: failed to launch app"

iv looked everywhere and can't find a fix

**Comment by SireNightFire** [comment]
it seemed to fix itself when i upgraded to Windows 10

**Comment by Kiro32** [comment]
Hi there, don't quite know why no one has commented on the issue in nearly a year but since I continue to have this problem in 2016, I'm bringing it up again.

"Connection Failed
Failed to launch app"

iPhone 5C, Windows 7, Gamestream ready PC powered by a GTX 970.

After moving from my old house recently, I noticed for the first time my Moonlight app actually recognizes the PC on my network (previously it showed nothing, and direct connecting through IP didn't work either) so I'd like to get to actually use this program now since this is the closest I've been to successfully using it. 

My device is paired through my PC and I correctly entered the code to make them paired. All the games on my PC show up just fine, but it's as if my PC doesn't get the command from my phone to start any of the them, please help!
