### ISSUE TITLE
Reinstall

### ISSUE THREAD

**Issue by festaman** [moonlight-stream/moonlight-ios#163]
I just got a mad cats crtli and wanted to test it with moonlight. I noticed it's not on my new replacement phone and I don't see it in test flight anymore. How do I get the beta back on?

**Comment by mrb113** [comment]
Hi festaman, 
It sounds like your beta may have expired. 
Since we're getting ready to launch on the app store (and also the beta is full), we're not accepting more beta testers at this time, but thanks for your interest in improving Moonlight! We understand that our users are anxious to start streaming games to their iOS devices, so join this email list if you want a notification the day it's available. (This is the only thing that email list will be used for) http://eepurl.com/btvkG9
