### ISSUE TITLE
L3, R3 and select on DS3

### ISSUE THREAD

**Issue by fran122157** [moonlight-stream/moonlight-ios#168]
Hi!

I´m using moonlight on a jailbroken iphone 5 (8.4) and my ds3 is connected through bluetooth with controllers for all.

the problem is that many games that use the R3 and L3 mappings (although they work), they do not recognize when these buttons are pressed in the control.

Also the select button acts as start in most of the games (I say most because I haven´t test most of my library)

Is this a problem with MFI controllers (as most of them do not have L3, R3 and select buttons)
is this fixable on ios using another solution other than controllers for all?

**Comment by shusain93** [comment]
This is a controllers for all issue. I also run into this issue too while playing games, so I'll contact the developer about it, maybe they can add custom mappings for select to get the disconnect onto a less used button like the PS button. 

Anyways, the L3 R3 issue is an MFI problem because Apple's controller spec doesn't include a L3 R3 so applications have no access to it.

Not a moonlight issue, by the way.

**Comment by fran122157** [comment]
Yeah, i thought so. I contacted the developer of CFA also and he told me the same you just said.
Currently the PS button is used to terminate the connection between the controller and the iOS device. The select button is mapped as a start button.

 Should I close this issue??

**Comment by shusain93** [comment]
Huh, that’s new. Probably should update my packages if that’s been fixed. The only option is that CFA developer implements a custom framework that works on top of the MFI system to send custom signals which apps could use for nonMFI inputs, but this should be brought up with the developer of CFA not here I guess. This could be really nice actually.

So yeah, I guess you should close the issue.
