### ISSUE TITLE
[Feature Request] Add bluetooth mouse support

### ISSUE THREAD

**Issue by SethAten** [moonlight-stream/moonlight-ios#173]
Similar to #37 , but more with the Jailbreak market. I use BTC Mouse and Trackpad to connect a Bluetooth mouse to my iPad. Having native support for both this mouse and a Bluetooth keyboard would enable full pc-like control for those who want to use limelight to play PC-style in locations inconvenient for desktop gaming, such as in another room or in bed.

**Comment by ZeroT3K** [comment]
At the very least keyboard support, which doesn't require jailbreaks. FFXIV ran wonderfully with my mfi controller when I was part of the beta, but still required a wireless keyboard in-range for chat. 

Mouse support for jailbreaked devices would be icing on the cake if it can pass certification.

**Comment by apocolipse** [comment]
There's unfortunately no public API for the AppStore that allows Mouse use afaik, and even keyboard use is limited at best (i.e. some things will be limited, like ESC is mapped to the Home button through the system so I don't think you can capture it and forward it).
With a jailbreak thats a different story, but as @ZeroT3K mentioned it can't pass certification.
I'm looking into writing a jailbreak tweak that would add support for HID devices (basic mouse/keyboard) as well as other bluetooth devices (dualshock controllers w/ clicky sticks!) to the iOS app, it would act as a compliment (directly injecting @ runtime) so that the main app is still a normal appstore app but with controller support added separately if you have a jailbreak.
Ideally the "best you can" approach to keyboard support should go into the main app with extras (like ESC capturing, etc) added externally.

**Comment by ajmi982** [comment]
Hey Chris. Thank again for updating moonlight to work on the Apple TV 4?

Question for you. Would you have the ability to update moonlight to allow full screen display on an iPad? I'd love to be able to get rid of the black bars on my iPad air 2. 

I'm jailbroken so I could side load the app using code most likely. 

Thanks.
