### ISSUE TITLE
Xbox 360 controller connected to the PC doesn't work

### ISSUE THREAD

**Issue by Axadiw** [moonlight-stream/moonlight-ios#182]
I've tested moonlight iOS with couple games, and it looks like some of them aren't supporting gamepads (Xbox 360 controller in my case), when they are connected directly to host PC.

I've tried it with GTA5, where gamepad is recognized perfectly. It's also working in Steam BigPicture client.

But when I've launched "Bioshock Infinite" and "Witcher 3", game isn't reacting for button presses on the pad ;( (actually in Bioshock I'm able to skip initial intro, but when main menu isn't working).

I've tried with Android version of Moonlight (I've plugged it into my AndroidTV), and it looks like the same issue is applying there as well. After plugging the XBox360 wireless adapter directly to the TV, everything works perfectly. The problem occurs when it's connected to the host PC.

Is it possible to tune this, so it will take controls from the host PC, instead of controllers attached to client machine? I guess that it might be Nvidia's issue, so maybe it's possible to tweak something there?

**Comment by Marvin91** [comment]
from: http://forum.xda-developers.com/showthread.php?t=2505510

Using a wired/wireless controller connected to the GFE PC instead of the streaming device
Normally, Moonlight sends controller input from the streaming client which gets sent to the game by GFE. If you want to connect a controller to your PC instead of the streaming device, GFE can cause some problems because the emulated controller still appears to games as controller 1. Luckily there is a workaround for this. You'll need to rename the DLL that Nvidia is using to send controller input so it won't be used anymore. On 32-bit and 64-bit Windows, rename rxinput.dll to rxinput.dll.old on in C:\Program Files\NVIDIA Corporation\NvStreamSrv. On 64-bit versions, there's another copy of the DLL in C:\Program Files (x86)\NVIDIA Corporation\NvStreamSrv which you'll want to rename. You may have to do the renaming again if GFE does an update, but it should allow you to use your controller normally on games that only support 1 controller.
