### ISSUE TITLE
Request: Screen resolutions for the iPad and iPad Pro?

### ISSUE THREAD

**Issue by Kanoonoo** [moonlight-stream/moonlight-ios#192]
Could you add screen resolutions that would work for the iPad and iPad pro? Right now if you play on the iPad, it letterboxes the games. I love your app btw!

**Comment by basvroegop** [comment]
I've been wondering the same. I did notice some footage of people who got a 4:3 resolution working on the iPad, but it doesn't seem to work here. When I change the in-game resolution, it just makes the game look weirder in the initial 16:9 resolution. Changes back to a 16:9 resolution when rebooting the game.

**Comment by guering** [comment]
I strongly second this request. The app is wonderful and my only issue is that no matter how I tried I couldn't get the games to run at fullscreen on iPad (4:3, 2048x1536). Then I noticed the iPad app only has two options to choose from (720/1080), so I'm guessing the app client is the one limiting it to 16:9. I've seen a [thread on the Android app page](https://github.com/moonlight-stream/moonlight-android/pull/123) which apparently solves this. I hope we can get more options too. Thanks again for the incredible work guys.

**Comment by angrycrab** [comment]
Same problem with my Ipad pro. Moonlight always runs with black bars on top and bottom of the screen.
Is there a way to remove the black bars?

**Comment by jpecih** [comment]
I would even pay for this feature!
It would be a killer app for Ipad Pro!

**Comment by Malexirian** [comment]
I'd like fullscreen stream on my ipad air too! Pleeeeaaaaase :)
cheers for the great app!

**Comment by jpecih** [comment]
At leat, if possible, an scale to fit screen option would be great, like in android version.
Thanks again for a terrific app.

**Comment by flaxfoot** [comment]
Would be willing to give additional donations for this option !

**Comment by Aghassi** [comment]
@flaxfoot We appreciate the offer, but we don't accept donations at this time. If you wish to donate, please see the foot of our website. We encourage donations to the University at which Moonlight was first developed. We will be looking into iPad Pro support in the future. It is definitely on the list of things to support.

**Comment by ajmi982** [comment]
Any progress on this? Would be incredible to get full screen gameplay on my iPad air 2. Thanks.

**Comment by cgutman** [comment]
The challenge is that modern versions of GeForce Experience won't allow you to stream a resolution unless your physically attached PC display can be set to that resolution too (with a slight exception for 4K). Unless you have a 4:3 display connected to your PC, streaming at a 4:3 resolution won't work.

**Comment by guering** [comment]
> Unless you have a 4:3 display connected to your PC, streaming at a 4:3 resolution won't work.

I suppose there's more to it than just changing the display to resolution to 4:3? I've tried that (through Nvidia's force resolution) with no success.

**Comment by D88isaac** [comment]
Yes, please halp! The letterboxing on my iPad Air 2 is something I would gladly pay to have fixed.

**Comment by maddox** [comment]
how many modern games even support a 4:3 aspect?

**Comment by D88isaac** [comment]
Are there any workarounds or alternative apps? I have the same problem, going into 4:3 resolution just makes the letter-boxing worse than 16:9 resolutions.

**Comment by jpecih** [comment]
Praise God I found a workaround. (TEsted on IPAD pro wifi 32, 9.3.3 jailbroken)

1. Uninstall current GFE version.
2. Install version GeForce_Experience_v2.1.2.0
3.Block GFE updates by adding following line to C:\Windows\System32\drivers\etc\hosts
"127.0.0.1 services.gfe.nvidia.com"
4.Install Moonlight_0_9_2.ipa (Yes yo need jailbreak to do this)
5.Pair, everyhting. Then select Resolution: Native
6. An error message urgin you to change resolution to match you ipad pro will arise, just continue
7.Enjoy borderless moonlight!!

**Comment by ajmi982** [comment]
Where do we get that IPA file??

**Comment by jpecih** [comment]
You can find it in
"https://github.com/moonlight-stream/moonlight-ios/releases"

**Comment by Vahn84** [comment]
2 year gone from when the issue was opened

Is this something that will be addressed or not?

**Comment by Kanoonoo** [comment]
As the original poster of this topic, I say it won’t likely. I stopped using moonlight like a year ago because of the lack of this feature, it’s dissapponting on so many levels to see such an awesome app be ruined by an easily made feature request. 

Even if it wasn’t easy, two years would be more than enough time to figure it out and even if it weren’t enough time, it’s certainly enough time to allow the devs to at least comment here and update us. 

I reccomend that you just move on to another app or service. The creators of moonlight clearly give 0 Fs.

**Comment by cgutman** [comment]
We're limited by what GeForce Experience will stream to us. It only supports changing resolution to 720p, 1080p, or 4K at the moment.

These duplicate resolution request tickets get created all the time and we don't respond to them all.

**Comment by Kanoonoo** [comment]
Yeah I think it went without saying hat you don’t reply to them all. Mine was one of the first if not the first. 

Regardless of petty details, though, it’s nice to hear back from you, even if it is two years later. 

Your dismissive tone is super encouraging and creates an awesome social environment. 😘

**Comment by cgutman** [comment]
I was planning to make an FAQ page in moonlight-docs to address this one since I get so many questions about it, but I haven't done it yet. Between Chrome, Android, iOS, and PC, Moonlight has hundreds of open tickets and I just can't respond to them all myself. The hope is that people will discover the other tickets (and some do). Many of them are users will support issues that aren't Moonlight problems, others are feature requests like this that Moonlight can't fix without a GFE update, others are real Moonlight bugs or standalone Moonlight feature requests. Closing these wouldn't do any good since they would be less discoverable and it's still a valid feature request.

I understand it can be frustrating not to hear back. I'd probably be frustrated too if I were you. While there are more than a few of these tickets, remember this is a project run by volunteers who have real jobs and lives and make no money from doing this work. Sometimes there's just not enough time to go around.

**Comment by Vahn84** [comment]
Hi @cgutman thank you for your reply

clearly I've gone through many of the issues you're mentioning but didn't find a clear statement that could describe the state of thing like you're doing now. 

Is there a workaround? Or Geforce Experience always will stream a 16:9 signal  no matter what you do on pc side?

**Comment by cgutman** [comment]
There are 2 resolutions at play: display resolution and stream resolution. The display resolution is the resolution of the host monitor and the game and the stream resolution is the resolution of the stream to the client device. Typically, these should be the same.

GeForce Experience will happily change the stream resolution to whatever you ask it to. The problem is that the display resolution is limited to 720p, 1080p, or 4K even if your host monitor supports other resolutions. So you can request 2048x1536 from GFE but all you will get is 720p (display resolution) stretched to fill, using more bandwidth than just sending 720p.

You can change the display resolution in game manually to match the stream resolution if your PC display supports it. It's a crappy solution, but it's a possibility for requests like 1440p. For 4:3 and other weird aspect ratios and resolutions, it's highly unlikely you'd find a modern PC display that would support that.

Now you can workaround this too by creating a custom resolution in your Nvidia control panel advanced options, but at this point, the cost/benefit just isn't there. We'd need to entirely rewrite our settings UI in iOS just to support this one feature that would be difficult to use and errorprone anyway.

**Comment by Vahn84** [comment]
Thanks again for your time @cgutman 

I know that this kind of projects are mostly coded by people that has another life (their real life) so I will not ask you to do that xD

But, anyway...you're telling me that if I'd want it to (not likely xD ), I could work on it to add a button (labeled "custom" maybe) next to the others (720p, 1080p) that could open a dialog window, let me set a custom resolution and send it to the pc host to apply that custom res? Is there a way to remotely apply a custom resolution you usually edit inside the Nvidia control panels?

**Comment by cgutman** [comment]
Potentially, as long as the UI is nice (Apple is picky).

**Comment by anastasiuspernat** [comment]
Moonlight is still doing weird things on iPad, I'm not sure why this issue is closed. People stopped using iPad for streaming haha?

I have a monitor that supports 2048x1536 (iPad Pro 12.9" resolution). When I use this resolution in Windows 10 the most recent version of Moonlight displays picture only on the 1/4 part of the screen. But not for every game. For example if I use 2048x1536 in some Steam games (like Beat Cop) it's still 1/4th of the screen. But when I run Shadow of the Tomb Raider it looks totally cool using the full screen real estate. I can't see any noticeable artifacts, it does look great when it uses the whole screen!

So it seems there's an issue on how Moonlight interprets data from GameStream. @cgutman said that we can change monitor's resolution and still Moonlight will not support it...but it does support it for _some_ games.

Or is it a GameStream issue? How do I set it up to use full screen in all games? Thank you.

**Comment by anastasiuspernat** [comment]
I seem to have found a workaround! Before launching a game I went first to Windows Display settings and set resolution to 2048x1536 and then to NVidia ```Control Panel -> Adjust desktop size and position``` and set Scaling to Full-screen and then Apply. After that when I launch a game it works properly. But this has to be done every time before launching the game. Couldn't find a way to set it permanently.

**Comment by mhvuze** [comment]
@anastasiuspernat Care to share some more details? I have set my monitor to a 4:3 resolution and have set scaling to full-screen in the NVCP. However, once I start Steam through Moonlight (and any game through it), it falls back to  16:9.  I only have 360p/720p/1080p resolutions to choose from on my iPad Pro 12,9" 2018. Not sure what I'm missing.

**Comment by simeonivanov** [comment]
Just a heads up, Steam Link is now available on the iOS and it's diplaying all the games in full screen. So give it a whirl.

For some reason Steam Link on my iPad Air 2 has connection issues, hiccups and such. I don't have these  issues when using Moonlight. And I don't have these issues when using Steam Link on my Android device, go figure.

However, I have found a workaround for having full screen games on Moonlight using Steam Link, follow these steps:
- Open the game you wish to play via Steam Link.
- Open Moonlight and connect to the same game, you should now see that the game displays full screen. YAY!
- At this point, you can kill the Steam Link app if you think it might take up extra bandwidth. From what I see, the stream seems to pause on Steam Link, so this should not be necessary.

Though I really hope that the Moonlight devs could reconsider and implement a proper fix for this.

Hope this helps!

**Comment by Silithas** [comment]
Same issue here. There´s only 16:9 aspect ratio options in the app, and as my ipad pro 2018 is 3:4, then it adds thick letterboxes. Would appreciate it to have 1600x1200 or similar 3:4 ratio resolutions.

**Comment by neronmoon** [comment]
Same issue! Pls fix!

**Comment by Silithas** [comment]
I found out that witcher 3 worked to have close to ipad's res or at least aspect ratio. So it has to be the game that needs to support the res. It's like having a 4:5 ratio monitor or 16:9, but old outdated game only has 4:5 ratio res, the game needs to support the res, or the monitor will have an odd aspect ratio.

So find the game's config files and manually "force" the game to have the res you want, and see if that works. (you can force the res with google remote desktop through google chrome which is what i use to prepare my pc for gaming on the ipad through the ipad on the go)

**Comment by Esvent** [comment]
Same issue here.

I have a iPad Pro 12.9” with 2072x2048 resolution. I want to streaming my desktop with native resolution.
So I trying to add a custom resolution (2072x2048) on Nvidia Control Panel and use Moonlight with 4k option to stream it. It works, but not perfect. The streaming of moonlight is more blurrier  than other streaming app like SteamLink. I guest it’s caused by host display resolution (2072x2048) is different with streaming resolution (3840x2160).

If we can have a “Native” or “Custom” option for streaming resolution on Moonlight would be nice.

Thank you for your amazing work.

Moonlight vs SteamLink @ 2072x2048
![DD203903-3AEB-486B-AAD9-007C7BC3A08B](https://user-images.githubusercontent.com/7689359/79226530-22f41280-7e91-11ea-9d37-5263fdbd0d73.jpeg)
![E5D59D6B-3627-4D26-94CC-09D1825C13A7](https://user-images.githubusercontent.com/7689359/79226541-28515d00-7e91-11ea-90f1-161a34933055.jpeg)

**Comment by AlexanderPavlenko** [comment]
@Esvent 
> I guess that it’s caused by host display resolution (2072x2048) is different with streaming resolution (3840x2160).

I solved this by using a larger custom display resolution while keeping the desired aspect ratio. In your case it is (2160 / 2048 * 2072)x2160 which is 2186x2160

**Comment by Esvent** [comment]
@AlexanderPavlenko 
> I solved this by using a larger custom display resolution while keeping the desired aspect ratio. In your case it is (2160 / 2048 * 2072)x2160 which is 2186x2160

That’s fantastic!

Just tried this workaround, now I can get the streaming quality very close to 1:1 streaming, which is definitely better than 2732x2048 via 4K.
Thanks a lot!

P.S. The iPad resolution on my earlier post is wrong, the correct one is 2732x2048. So the workaround resolution should be 2882x2160.

**Comment by xxxxxxx12345** [comment]
> I seem to have found a workaround! Before launching a game I went first to Windows Display settings and set resolution to 2048x1536 and then to NVidia `Control Panel -> Adjust desktop size and position` and set Scaling to Full-screen and then Apply. After that when I launch a game it works properly. But this has to be done every time before launching the game. Couldn't find a way to set it permanently.

Thanks!!! this actually worked for me, with one minor tweak though, when I'm playing a game (I've only tried Fortnite so far), I have to set Fortnite's ingame screen mode from Fullscreen to Windowed Fullscreen and that's it. Otherwise Fortnite will force you to use standard 16.9. Btw if anyone is on a 2nd gen 10.5" iPad pro  like me the correct picture size is 2224x1668.

**Comment by Jiankun-Huang** [comment]
I found out by opening Nvidia Control Panel then going to display. You can add a custom resolution without breaking your computer! Just match the IPad Display Resolution.
