### ISSUE TITLE
App no longer connects

### ISSUE THREAD

**Issue by Amir-Hass** [moonlight-stream/moonlight-ios#233]
The first time I opened the app my PC was already paired and everything was working perfectly, however, one day it showed that my PC was offline and it actually wasn't so I removed it and tried to readd it but it kept failing. I reinstalled the app and still had no luck. Please help because otherwise you have a solid app!

**Comment by firstIssue** [comment]
Hey there. Someone else suggested, that the reason could be the version of GFE. I tried some different versions and came up with deleting the whole Nvidia stuff, installed the driver manually with clean install and installed the version GeForce_Experience_v2.10.2.40 , which is still working after some restarts. Now my computer seems to be online everytime I try to stream from it. GFE just updated itself because I did not untick the auto update box, but is still working after some restarts. So maybe, try to delete everything, install my suggested version and let GFE do its thing. BTW, I did not log in as this could corrupt the way, GFE is trying to connect to SHIELD "like" products, instead of using IP trying to use the account name or whatever.
