### ISSUE TITLE
RTSP Handshake failed with error -1

### ISSUE THREAD

**Issue by Gamma111** [moonlight-stream/moonlight-ios#272]
I am able to connect via wifi perfectly fine but whenever I connect using data the game would load on the screen and I am greeted with the error in the title.

I've set up port forwarding and double checked but its still not working. I've added a rule to windows firewall and that's not working either.

**Comment by FlamingJampack** [comment]
I am having the same issue. I was able to work around port forwarding but now I get the error of -1. Connected to wifi it works fine 100%, but when I try to do it over the internet the computer starts opening the game but the phone is not receiving anything

**Comment by mspencer123** [comment]
I get this over wifi using an iPhone 6.

**Comment by gt2416** [comment]
Same, using iOS 11.2.1. Tried DMZ, port forwarded all the ports nothing works.
Also my PC cant be found using my dns address although sometimes it works, its spotty.

**Comment by cgutman** [comment]
@gt2416 is yours also over WiFi?

If you're on the same network and getting this, it's likely a firewall issue preventing the traffic from getting through: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#firewall-setup

If you only get this when streaming over the Internet, it's probably a port forwarding rule mistake: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#unable-to-stream-over-the-internet

**Comment by gt2416** [comment]
I only get the problem over the internet. I have tried re forwarding the ports a couple of times. Deleted all settings / re did it / double checked everything etc. Its weird sometimes I can connect and video works smoothly BUT only for 1-10 seconds, after that no video but sound / control is maintained.   : / 
Otherwise I get RTSP error.  
Like I said I have tried DMZ so cant be a port forwarding issue. Also I tried the port check tool and it checks out. Im using a verizon router and added my dns server (no ip) to the dynamic dns list.
If I use that I get the weird behavior I mentioned above. If I use my direct ip, I get a RTSP error ALL the time.
