### ISSUE TITLE
Support higher than 1080p streaming and HDR streaming (HEVC with IOS11 (even 10bit HDR))

### ISSUE THREAD

**Issue by oscarbg** [moonlight-stream/moonlight-ios#277]
Hi,
just purchased Ipad Pro 10.5 2017 with A10X and jointly with IOS11 supports HEVC (even 10bit samples) HW decoding..
As Gamestream supports HEVC 10 bit for HDR streaming and also this Ipad has screen higher res than 1080p it would benefit perhaps from 1440p streaming  not much 4k..
anyway Moonlight works perfect but as said would like to see option to stream in 1440p and even 2160p for testing and also IOS client to be capable of advertising HDR support via HEVC codec..

thanks..

**Comment by MichaelMKenny** [comment]
I totally agree. I also have an iPad Pro 10.5 and was hoping Moonlight would adopt HEVC. As for 1440p and 4K that's pretty easy to implement, I been running a custom build of Moonlight for over a year now that I made that supports those resolutions. The only thing is, is that to allow it to work you have to set your desktop resolution to match the setting on the iPad.

As the iPad Pro is so powerful I can achieve 1440p @60fps no problem, but it would be nice if Moonlight officially adopted higher resolutions and new video decoding methods. Moonlight hasn't been touched in while, so here's hoping development starts back up soon.

**Comment by cgutman** [comment]
Moonlight development is doing fine. When the iOS 11 SDK is finalized, we will release a build supporting HEVC. It's a trivial addition to the code.

**Comment by cgutman** [comment]
HEVC is supported in master on A9 devices and later running iOS 11. The issue with custom resolution support is that GeForce Experience really doesn't work well with resolutions other than 720p, 1080p, and 4K. It can stream those resolutions even without host display support, though it requires it for any other resolution. Also since it's not designed for it, you don't even get a way to know whether the server can even give you what you're about to ask it for until you try and it blows up (or worse, just streams 720p upscaled to 1440p for high bandwidth usage for no benefit).

As far as I know (and I tried as recently as 2 weeks ago), there's no way to force GFE to change the active display resolution (let alone to an unsupported resolution). I haven't even gotten it to change active resolution to _any_ custom resolution, even one supported by my display.

**Comment by oscarbg** [comment]
Good news.. will test ASAP.. any comments on HDR game streaming? might make sense for new IPhone X with HDR screen / video support..

**Comment by cgutman** [comment]
There are very few games that Nvidia supports streaming in HDR. I have done some experiments where I did successfully receive an HEVC Main10 video stream, but the actual capture was still SDR.

**Comment by oscarbg** [comment]
thanks any TestFlight Moonlight beta channel to enroll or to check this HEVC support must build from source?..

**Comment by cgutman** [comment]
You must build from source. There's no TestFlight beta ongoing now.

**Comment by cgutman** [comment]
HEVC released in v1.4.0

**Comment by oscarbg** [comment]
nice..
can add a select códec toggle (so we can select H264 also even in supported HEVC devices) just for testing..
also I have Shadow Warrior 2 which is one of the few HDR games to test.. checking device logs I see:

Sep 27 11:12:38 iPad-de-oscar Moonlight[6680] <Notice>: <INFO> Constructing new HEVC format description but can't see if it's Main10 or not.. 
how to know?

also about Main10 requires a Pascal GPU right.. I have Maxwell GTX 970 so perhaps can't test HDR streaming right now..

also Moonlight could add some "stats for nerds" similar to YouTube that printed a overlay showing current codec (HEVC/H264 and if it's Main10 or not and also current BW usage Mbps) and resolution used..
