### ISSUE TITLE
A suggestion for  active L3/R3 button by using mfi controller 

### ISSUE THREAD

**Issue by 4moonlight** [moonlight-stream/moonlight-ios#283]
In playmira(APP for steaming ps4 in ios)，it work perfectly by this way——Creat a buttoncombo for simulate L3/R3，for example i click R1 and R2 at the sametime,which can active  the R3 button.
Is there are possible to work in moonlight for using mficontroller?

**Comment by 4moonlight** [comment]
eh... will moonlight still be update in future？

**Comment by 4moonlight** [comment]
i ask for the controller for all developer,but seems like it can work in that plugin，so the only hope is moonlight can support it.

**Comment by 4moonlight** [comment]
Another suggestion，if the buttoncombo solution did not work,can increse a option of auto onscreencontroller ？such as translucence and setting position. thanks for yourguys wonderful work !

**Comment by 4moonlight** [comment]
hello,is someone there?

**Comment by Dentifreak** [comment]
it seems to be dead...no feedback on posts...

**Comment by cgutman** [comment]
Just because we're not actively responding to feature requests within a few days doesn't mean the project is dead. I just pushed a series of bugfixes here 4 days ago.

Remember that we work on this in our spare time after we get home from our real jobs.

**Comment by 4moonlight** [comment]
sorry for that.Thanks for you guys amazing work,moonlight is a fantastic app.

**Comment by 4moonlight** [comment]
Android version is better.

**Comment by cgutman** [comment]
We're just limited by Apple's MFi specification here. Even with a magic key combination (which I'm sure people would want to configure, creating more UI/UX headaches), then what do we do when we get it? Toggle R3/L3? Tap R3/L3? What if you really do want to press R2 and R1 at the same time? Can you toggle off the combo in game? 

Most MFi extended gamepads have analog triggers, so timing a R1+R2 press is going to be a pain since the actuation point will vary with the physical hardware.

We _do_ have magic button combos for Select (Play+L1) and Special/Mode (Play+R1), but those are infrequently used and there's not a concern that somebody might want to do something else other than tap Select or Special in that case.
