### ISSUE TITLE
Black screen when connected, audio still plays

### ISSUE THREAD

**Issue by Dribblejam** [moonlight-stream/moonlight-ios#291]
Having an issue with moonlight. Audio plays on my device but the video is black. Strange thing is, this only happens with steam big picture and exe’s that I added manually. Games the gfe finds automatically work fine.

**Comment by cgutman** [comment]
Yeah, this was introduced in GFE 3.10 and impacts certain streaming settings. What resolution and FPS are you streaming?

We have a build submitted to Apple to fix this.

**Comment by Dribblejam** [comment]
I was playing at 1080 60fps. Can’t believe the update just hit the AppStore. Amazing response time to issues!

**Comment by Dribblejam** [comment]
Just tried said update but the issue stills persists. Tried different configurations but no luck.

**Comment by cgutman** [comment]
Can you reproduce the issue, then zip the logs in C:\ProgramData\NVIDIA Corporation\NvStream and link them here?

ProgramData is a hidden folder so you may need to enable hidden files and folders to see it.

**Comment by UprisingPulse** [comment]
Hi, i have the same issue, black screen in every game i try to stream
this is my log
[Log.zip](https://github.com/moonlight-stream/moonlight-ios/files/1499972/Log.zip)

**Comment by cgutman** [comment]
@UprisingPulse According to these logs, your display is connected to your Intel integrated graphics and not your NVIDIA GPU. Your NVIDIA GPU must be your primary display and connected to a monitor for GameStream to work.

> #8(I)[2017-11-23 17:37:14,734]=01:37:14={00005F98}<MainServerThread> Head 0: DevName \\.\DISPLAY1, DxAdapterOrdinal 0, DevString 'Intel(R) HD Graphics 630'. AttachedToDesktop MonitorConnected 
#9(I)[2017-11-23 17:37:14,734]=01:37:14={00005F98}<MainServerThread> Head 1: DevName \\.\DISPLAY2, DxAdapterOrdinal 0, DevString 'Intel(R) HD Graphics 630'. 
#0(I)[2017-11-23 17:37:14,734]=01:37:14={00005F98}<MainServerThread> Head 2: DevName \\.\DISPLAY3, DxAdapterOrdinal 0, DevString 'Intel(R) HD Graphics 630'.

**Comment by UprisingPulse** [comment]
@cgutman i connected to external monitor using HDMI, but still same black screen
[log2.zip](https://github.com/moonlight-stream/moonlight-ios/files/1501281/log2.zip)

**Comment by cgutman** [comment]
@UprisingPulse Do you have *any* monitors connected to your Intel GPU? You should disconnect all monitors from your integrated graphics and connect them only to your NVIDIA GPU.

**Comment by genius100** [comment]
@cgutman I have Laptop so i don't think I can disconnect the display.
but all games are working only this CEMU is not, while it is working for my friend, also anything related to streaming the whole desktop is not working.

**Comment by UprisingPulse** [comment]
@cgutman I have Laptop so i don't think I can disconnect the display.
but all games are working only this CEMU is not, while it is working for my friend, also anything related to streaming the whole desktop is not working.

**Comment by christiansam** [comment]
As you described the issue occurs when non-steam games beign started from within BPM. It 've noticed similar issues (audio working, black screen) when trying to use (Steam's) In-Home-Streaming to run non-steam games, located on non a third computer, out of my moonlight session.

I 'm currently using this workaround: Instead of launching Steam directly from moonlight‘s home screen, add a starter for Windows Desktop (c:\windows\system32\mstsc.exe) in GFE’s Shield settings, and start Steam manually when being connected to your Desktop. Run any non-steam game and try if the black screen error is gone. 
Please note: You might notice that controller input won‘t work when using mstsc.exe as your „launcher“ to start Steam. A workaround for this is to change mstsc.exe e.g. with an „real“ application launcher like „Gamesroom“ - or any other application that has built-in controller support. In case of Gamesroom, you have to manually enable it in settings. Then add an launcher entry for Steam.exe and everthing should work as expected.

**Comment by henderburn** [comment]
Hi - I’m still encountering this error (black screen, sound) on the latest iOS build, and unfortunately the workarounds don’t work for me. MSTSC.exe also launches as a black screen. The GPU selection shouldn’t be an issue because my i7-5930k has no integrated graphics. I updated to the latest Nvidia driver last week, and have the latest Win10 updates. Any thoughts?

**Comment by schlafnase** [comment]
I have a similar problem I want to play with my brother loal coop over the internet but when I enter the code in moonlight to allow him to connect to my PC he can only hear the sound of the game but sees a white screen but no error message. When I try it with a friend it works no problem does anyone have a idea why?

**Comment by NullReferenceError** [comment]
I’ve noticed this issue when my main computer monitor is powered off.  I wonder if others are experiencing it when similar situations occur?  My monitor has to be on, or have a sleep setting enabled and woken from sleep to prevent the issue.

**Comment by perog** [comment]
I get the same result as what NullReferenceError wrote: when the computer monitor is off I only get a black screen, but sound an clicking works. I would rather not have the screen be on all the time, plus it is mirroring everything I do from remote, so is there a way to use moonlight even if the monitor is off?

**Comment by cgutman** [comment]
@perog You can get a cheap headless HDMI dongle from Amazon. That's what I do for my test machines.
