### ISSUE TITLE
Implement the ability to configure keystrokes for on screen input buttons?

### ISSUE THREAD

**Issue by Proaxel** [moonlight-stream/moonlight-ios#302]
I decided for the heck of it try to open my modded Minecraft game while I was streaming my entire desktop. I was curious to see how playable it would be. I was presently surprised to find that it is pretty close.  Through this I did notice that the on screen controls are set to do certain key strokes to the host. For example, the L2 and R2 buttons left and right click, the B button does a spacebar, L1 presses Control, and Start presses Escape. The right stick moved the cursor. Because of this I was able to do a few essential actions like place blocks. Unfortunately there wasn't any way to do WASD input, so I couldn't move the player around. 

Is there some way one can change these on screen controls to do different keystrokes than the ones set up by default? For example, I want to set up the DPad or left stick to use the WASD keys, and A to use Spacebar. If not, is it possible we can have this sort of feature implemented? This feature alone can make quite a few simple games a lot more playable if we could simply access keyboard inputs with the on screen controls!

**Comment by christiansam** [comment]
Give Steam's sophisticated input mapping-functions a try. Nvidia Shield instantiates a virtual XBox360 Controller on your host computer - at least when using a MFI-controller with your iPhone/iPad, but i think Moonlight's on-screen controller should do it too.

Since Steam opened its once Steam Controller only mapping-features to Playstation an XBox controllers just setup the virtual XBox360 in Steam's BPM controller settings and afterwards configure your controller-to-keyboard mappings in your game shortcut specific controllers settings.
