### ISSUE TITLE
battery save option for ios?

### ISSUE THREAD

**Issue by dennore** [moonlight-stream/moonlight-ios#303]
is there a battery safe option for ios (like on android)
my phone is draining energy so fast and getting hot even on 720p and 30 fps 2.0 Mbit

**Comment by cgutman** [comment]
Interesting. The reason the Android version has a "battery saver mode" is because there are some threads spinning doing nothing in the background to keep the CPU from throttling so low that it starts dropping frames. This is due to CPU governor issues in older versions of Linux that many Android devices use. These threads artificially inflate the CPU load to keep the CPU at a higher frequency and burn extra power in the process.

On iOS, the governor has never caused noticeable problems so those threads don't exist. The battery draining is caused by Moonlight doing its streaming work. Last time I looked, Opus decoding was the largest CPU usage process within Moonlight. There are Opus changes in newer versions of the libopus library that may increase decoding speed and reduce CPU usage. I will need to investigate again to see what else is possibly hogging CPU time.

FYI, Moonlight will always have higher battery drain than simply watching a video, because Moonlight is waking up the network for every single frame, rather than downloading a chunk of frames and letting the network connection idle. We have to do this in order to keep the latency low.

**Comment by dennore** [comment]
Hey cgutman,

thanks for the detailed explanations...
the nvidia interface does not give options for a custom framerate/resolution for low performance. like 15fps? :-) maybe unplayable anyways... 

keep up the great work 👍
regards dennore
