### ISSUE TITLE
RTSP handshake failed with error 35

### ISSUE THREAD

**Issue by ParanoidEye3** [moonlight-stream/moonlight-ios#308]
Hey everyone, I'm trying to get Moonlight to allow streaming to my iOS tablet, and I can get it to function just fine while at home on my own Wi-Fi network. When trying to use a different network however, I receive the error "RTSP handshake failed with error 35"

I have opened up ports 47984, 47989, and 48010 on my router and firewalls as TCP. Verified that they are open as well from canyouseeme.org. I have opened ports 47998, 47999, 48000, 48002, and 48010 as UDP as well to make sure I receive audio.

Originally I tried streaming over IPv4 and received this error, so since both my home network and my tablet get 10/10 for IPv6, I decided to install the GameStream IPv6 Forwarder, however receive the same error message.

I tried disabling my firewall all together on my PC to make sure I didn't miss something there, I have uninstalled GeForce Experience on my computer and performed a fresh install, I have deleted the computer from moonlight and manually added with my IPv6 address and still receive the same errors.

I'm at a complete loss at this point, and any help would be most welcome!

**Comment by Proaxel** [comment]
I just reinstalled GeForce Experience earlier today to troubleshoot a problem with an unrelated program, and now I am getting this exact same issue too. The game starts up on the host computer, iOS client says "RTSP Handshake in Progress" for about 5 seconds, then it errors out with "RTSP handshake failed with error 35."

I'm just relieved I'm not the only one with this issue. @cgutman

**Comment by ParanoidEye3** [comment]
Are you using cellular data? The only way I have gotten around the issue is by connecting to a Wi-Fi connection. While this ultimately defeats the purpose for me as I am no longer where I want to be for streaming, it did get rid of the error.

**Comment by Proaxel** [comment]
Yes, I was using cellular data.  But now I have figured out the problem, at least for me! I decided to take a quick look at the setup guide again in case something changed, and what do you know, it did. Apparently, it changed from the first time I set it up; The ports that need to be forwarded in order for it to work have changed in some newer version GeForce XP. By reinstalling it I upgraded to that new version, so it turns out I just needed to change the ports to have it work on that new version. 

I don't know about you though... you say you have all the correct ports open, but it's still not working... Maybe try taking a good hard look again to make sure they are all typed correctly? I had that problem when I was first setting this up, I had a typo in two of the ports. Maybe also take a screenshot of the settings so we can verify that it's all correct? Good luck!

**Comment by Fhanchan** [comment]
Geforce: 3.13.1.30
Moonlight app: 1.8.0
iPhone 7: 11.2.1 (15C153)
Have the same error "RTSP handshake failed with error 35." and using cellular data. 
PC was paired and the game starts when clicking on the game. Then it gives the error.
I reinstalled Geforce, graphic card driver, and the app. Still have the same error.
Ports are all forwarded correctly according to setup guide. I also setup firewall according to the setup guide.
Please help.

**Comment by lucius2k** [comment]
Also experiencing another “RTSP handshake failed with error 35” error.
Only happens when using cellular data. It works when I’m on WiFi.

It’s funny, because cellular streaming was working when I was using Moonlight last year.

Moonlight iOS app: 2.1.0
Cell network: T-Mobile unlimited
iPhone X: 11.4.1
