### ISSUE TITLE
[Bug] Video/Audio Lag and Extreme input lag

### ISSUE THREAD

**Issue by JasonConig** [moonlight-stream/moonlight-ios#33]
I'm able to initiate a stream and select games, but, when the game starts, the lag begins. 

I'm not sure if I'm supposed to do this, but I'm using a wireless xbox controller to control the game. I understand limelight is meant to work with MFi controllers, but I only want to stream in the same room as my comp, so I figured I'd just use my existing controller (I have a mount for my 6plus on my xbox controller). It works perfect in the Steam menu. Virtually no input/video/audio lag (minus some audio cut-outs here and there), but everything changes when a game starts. It will not register input most of the time, and, when it does, it will receive one button press per 10, and repeat it. The video and audio also degrade dramatically. Sometimes the feed will just freeze altogether. 

I don't know what changing the bitrate does, so maybe I only need to change that. It may be the router, but I am getting 50mbs down and 50mbs up, and I have my computer wired directly to the router. Are there any settings in the router that I should change? Or my comp/app? 

Thank you for any help, and just let me know if you need more info!

**Comment by Carman-** [comment]
I have the same controller setup as you, and I was also experiencing bad input lag. This thread helped solve the issue.

Link:  http://forum.xda-developers.com/showthread.php?t=2505510

“Using a wired/wireless controller connected to the GFE PC instead of the streaming device

Normally, Limelight sends controller input from the streaming client which gets sent to the game by GFE. If you want to connect a controller to your PC instead of the streaming device, GFE can cause some problems because the emulated controller still appears to games as controller 1. Luckily there is a workaround for this. You'll need to rename the DLL that Nvidia is using to send controller input so it won't be used anymore. On 32-bit and 64-bit Windows, rename rxinput.dll to rxinput.dll.old on in C:\Program Files\NVIDIA Corporation\NvStreamSrv. On 64-bit versions, there's another copy of the DLL in C:\Program Files (x86)\NVIDIA Corporation\NvStreamSrv which you'll want to rename. You may have to do the renaming again if GFE does an update, but it should allow you to use your controller normally on games that only support 1 controller.”

Hope this helps.

**Comment by JasonConig** [comment]
Thank you to both of you for responding. I know this is extremely late, but I have been too busy to get around to testing your solutions. I will give them a try tonight and let you know the results. Thank you again for the help!

**Comment by dwaxemberg** [comment]
Can you please update on the situation? Are you still having issues with the latest version?

**Comment by greensouth** [comment]
I will try it today!

**Comment by dwaxemberg** [comment]
Please post an update on this issue, or it will be closed.
