### ISSUE TITLE
can i use Bluetooth keyboard on ipad to play games？

### ISSUE THREAD

**Issue by MDANDYW** [moonlight-stream/moonlight-ios#337]
if not will the app get this function in the future？  thx

**Comment by cgutman** [comment]
This is implemented and will be in the next release. However, there are limitations due to the iOS keyboard API that makes it not really suitable for certain types of games, like those where you use WASD to walk, etc. Since iOS only registers keys typed, not keys pressed/released, we can only send a down+up event for each key typed. In some games, this causes the character to move slowly.

**Comment by aceyu** [comment]
Is there any way to solve the issue, walk slowly by pressed WASD. or has any plugin in Cydia?

**Comment by MDANDYW** [comment]
Is there any possible solution? Does this mean the up or down keys are also behave like WASD?
