### ISSUE TITLE
"RTSP handshake failed with error 35" caused by cellular carrier blockages

### ISSUE THREAD

**Issue by Proaxel** [moonlight-stream/moonlight-ios#340]
Well, just as I thought I never had to visit this site again, this damn error comes back and better than ever. Only happens over LTE, problem does not occur on local wifi. 

- GeForce Experience Version and specs:
![image](https://user-images.githubusercontent.com/9545347/46190009-81a16d80-c2a6-11e8-8716-9dfbd1a31275.png)

- All ports forwarded correctly, including 48010:
![image](https://user-images.githubusercontent.com/9545347/46190177-494e5f00-c2a7-11e8-8e07-58a20e4f5048.png)

- Using the latest iOS app version (2.1.0)

- canyouseeme.org is reporting no problems seeing the open ports.

I hate to ask again for the millionth time, but can someone help me once more?

**Comment by cgutman** [comment]
Interesting, I also have T-Mobile and I'm still able to stream over LTE. Are you able to reproduce the issue if you tether to your phone?

**Comment by Proaxel** [comment]
I tried tethering my old Macbook Pro to my phone. Video was nothing but a black screen so I couldn't see anything, but audio and mouse keyboard input were coming through fine (albeit a bit stuttery). Tried it through my phone immediately afterwards, still the same error without VPN, works fine with VPN on. @cgutman Where to from here?

**Comment by cgutman** [comment]
Are you connecting with a host name or an IP address?

**Comment by Proaxel** [comment]
@cgutman Not sure, I'm guessing by that you mean what do I use when I first added the machine? In that case, I use the IP Address I got from whatsmyip. I didn't even know you can use a host name.

**Comment by MUSE-iC** [comment]
Im also experiencing the same issue with Tmobile. This has been an issue for the longest time back when the error was called "RTSP handshake error -1". As has been stated a VPN works, but its not a proper solution since VPNs can be fairly slow.

**Comment by cgutman** [comment]
Please retest with Moonlight iOS v2.4.0 when it becomes available on the App Store (currently waiting for review). I made a change there that might fix the issue.

**Comment by wamei** [comment]
@cgutman 
I had the same issue "control stream establishment failed error 35" on my iPhone. 
Now it was solved by new Moonlight app v2.4.0. Thank you!!

**Comment by cgutman** [comment]
The issue here was a [change/bug introduced in iOS 10](https://openradar.appspot.com/28378416) in `getaddrinfo()` in iOS 10 plus carriers switching to IPv6-only deployments using NAT64 for IPv4 connectivity.

Moonlight had always requested IPv4 addresses first for a long time, because GeForce Experience doesn't natively listen on IPv6. The idea was that in an IPv6/NAT64 environment where no local IPv4 address was available, `getaddrinfo()` would fail when requesting an IPv4 address (because we pass AI_ADDRCONFIG), then we'd fall back to asking for IPv4 or IPv6 and get an IPv6 address. This broke when `getaddrinfo()` started unexpectedly succeeding for IPv4 and giving us back an address that was totally useless.

No carrier blocking conspiracy for this, just a bug in iOS combined with more carriers going to IPv6-only setups due to the lack of available IPv4 addresses.

**Comment by Proaxel** [comment]
@cgutman Thanks for your hard work!
