### ISSUE TITLE
120FPS Not Discernible 

### ISSUE THREAD

**Issue by zakarupon** [moonlight-stream/moonlight-ios#372]
I’m currently using a 2018 iPad Pro 12.9” with Moonlight 2.7.0. I have a monitor that runs at 120hz and when I use the 120fps option on my iPad, I notice that the level of smoothness is nowhere near my PC. After making sure PC was connected via Ethernet and iPad via 5Ghz, I ran a few tests such as switching between 60fps @ 720p and 120fps @ 720p (to ensure bandwidth wasn’t an issue) across a number of games and found that there didn’t seem to be a difference. I even used the Blur Busters UFO frame rate test via chrome on my PC and found that while the difference between 120fps and 60fps on my Monitor was night and day, there seemed to be little to no difference at all on the iPad running moonlight at 120fps.

Without any performance stats it’s hard to really provide concrete evidence but it seems as though the 120fps option isn’t working. Is this just me or is anyone else facing the same issue? To test just run the Blur Buster UFO test on a 120hz+ monitor and stream that same monitor to the iPad at 120hz and the difference is quite visible.

**Comment by cgutman** [comment]
Is HEVC enabled? What's the host GPU?

**Comment by zakarupon** [comment]
HEVC is enabled and the host is an RTX 2080 Ti so I’m pretty sure the issue doesn’t lie there...

**Comment by cgutman** [comment]
Ok, I have a few things we can try. Do you have a Mac that you can use to test apps on your iPad? I don't have an iPad Pro to test with.

**Comment by zakarupon** [comment]
Sorry for the late reply. I do have a Mac, but you’ll have to walk me through the steps. Additionally, I just updated the Mac to the Catalina beta and the iPad to the iPadOS beta as neither are my main devices so I’m afraid that might hamper the reliability of any data I can provide.

**Comment by wajubalo** [comment]
I am curious about this. I also cannot discern if the iPad pro is outputting 120fps. I have the same GPU. Were you able to fix your issue?

**Comment by zakarupon** [comment]
Unfortunately it hasn’t really changed. It’s been a while but the last time I checked it still seems that the difference between 60fps and 120fps on my iPad is nonexistent but clearly visible on my monitor.

**Comment by susemeee** [comment]
I've been figuring out what's going internally and found something important about using true 120Hz.

I assume that a refresh rate of the display connected must be 120Hz to 'stream out' actual 120Hz video so that a client can view 120fps. In other words, if you set a refresh rate (between a graphics card and a monitor) to 60Hz, the client only receives output of 60Hz and then send it to the client with 120Hz video, even though the client is set to receive 120fps video.

When I forcefully put my graphics card output to 120hz (even if a monitor can't support so it just puts a black screen), using some custom [utility](https://www.monitortests.com/), 120Hz option appears in UFOtests and a UFO should be discernable.

I wonder if it's possible to configure display things from the moonlight client, things may be easier a lot if it's possible to do so.

**Comment by cgutman** [comment]
Try with https://github.com/moonlight-stream/moonlight-ios/commit/409b262a4fca80eb56df642eb5bd90dedccce6d5 and let me know if that has any effect.

If that doesn't work, I'm truly at a loss. We're clearly providing 120 frames per second to the AVSampleBufferDisplayLayer. If it's not redrawing 120 FPS on a 120 Hz display, that's really weird.

**Comment by zakarupon** [comment]
Ok so I just tried it today and it seems to be working. I put on the Blur Buster Frame rest on chrome then opened moonlight on my iPad and I can now see a difference between the 60hz and 120hz UFOs. It is not as discernible as on my monitor (which is probably due to the limitations of WiFi), but it’s definitely there.

**Comment by Silithas** [comment]
Same concern here. 120 fps option with 130 fps in the game still felt like 60.

**Comment by cgutman** [comment]
I did some testing today and the Metal profiler in Instruments confirms it is updating the screen at roughly 120 FPS. (It will never be perfectly 120 FPS because sometimes frames arrive late)

<img width="1030" alt="Screen Shot 2020-01-03 at 2 17 19 PM" src="https://user-images.githubusercontent.com/2695644/71746921-ddf12680-2e33-11ea-82a6-52f393e92739.png">

What you all may be seeing is microstutter due v-sync drift between the host PC and the client device. Even though both host and client are capturing/displaying at 120 Hz, that doesn't mean v-sync happens at the same time on both devices. Additionally, WiFi latency/jitter can cause the client to jump between being 1 or 2 v-syncs behind the host PC. Since the iPad is not an adaptive sync display, this causes frame intervals to abruptly jump between 8 ms and 16 ms (or more, if WiFi doesn't play nice). The "fix" for that is to buffer an extra frame in the rendering pipeline but that increases latency, so it's a tradeoff.

**Comment by yesacs** [comment]
Not sure if this is related but I’d figure I’d share it. I have an 2018 iPad Pro 11” and have been trying to debug a similar issue where games seem to only want to stream at 60hz. I discovered that when the moonlight client starts the game on the host machine, not matter what I have set in Windows, the refresh rate will revert to 60hz. The My Rig section in Geforce Experience confirms 60hz as the refresh rate. Once the connection is established I’m able to open up the nvidia or windows control panel, change the refresh rate back to 120hz, and then everything’s happy, includeding GFE’s My Rig now showing 120hz. What I found interesting is that this behavior also happens to me on the windows client. I have a laptop hooked up to a 120hz tv and I have to do the same refresh rate reset trick and after that it all works great. Some games (Dark Souls Remastered is one) will show a 120hz option, but it doesn’t actually work at 120hz until you manually change it in windows.

Apologies if this is known or is irrelevant.

**Comment by Silithas** [comment]
> I did some testing today and the Metal profiler in Instruments confirms it is updating the screen at roughly 120 FPS. (It will never be perfectly 120 FPS because sometimes frames arrive late)
> 
> <img alt="Screen Shot 2020-01-03 at 2 17 19 PM" width="1030" src="https://user-images.githubusercontent.com/2695644/71746921-ddf12680-2e33-11ea-82a6-52f393e92739.png">
> 
> What you all may be seeing is microstutter due v-sync drift between the host PC and the client device. Even though both host and client are capturing/displaying at 120 Hz, that doesn't mean v-sync happens at the same time on both devices. Additionally, WiFi latency/jitter can cause the client to jump between being 1 or 2 v-syncs behind the host PC. Since the iPad is not an adaptive sync display, this causes frame intervals to abruptly jump between 8 ms and 16 ms (or more, if WiFi doesn't play nice). The "fix" for that is to buffer an extra frame in the rendering pipeline but that increases latency, so it's a tradeoff.

but some of us uses a high end gaming pc where some of us like me has a 2080 that can easily nvidia gamestream 1080p 120 or 4k 60 even with 1Gbit datarate without issues, but where moonlight can't seem to show 120 fps over internet.

**Comment by neronmoon** [comment]
Seems like i have same issue, but i really thinks it's device problem. I seed 60fps on ipad 2018, but on iphone xs picture is freezing on ~15fps
So sad
