### ISSUE TITLE
Pinch to zoom and full screen on iPhone X/xr

### ISSUE THREAD

**Issue by johnblaze00** [moonlight-stream/moonlight-ios#374]
Can we get the ability to get pinch to zoom or force full screen on iPhone X/xr devices. 

Playing the Witcher 3 lately. So hard to read the texts. Some sort of zooming in option would he great

**Comment by Tekcry** [comment]
Find out your native iPhone screen resolution and add it as a custom resolution in your GPU control panel, then select that resolution in game. You can also change the HUD size (Options -> Video -> HUD Configuration -> Set HUD size to large).

That should make everything much clearer and easier to read in the Witcher 3.

**Comment by johnblaze00** [comment]
Thank you for the suggestion. Worked great!

**Comment by seanlennaerts** [comment]
Any plans to allow the user to fill the iPhone's entire screen (19.5:9). It would cut off parts of my 16:9 stream but might be nice in some games.

**Comment by Tekcry** [comment]
Refer to my previous comment, works for all the games I’ve tried. Much more effective than zooming in.

**Comment by PatiB87** [comment]
Unfortunately that solution does not work for e.g. emulators like CEMU.

Therefore I am still asking for the feature to set the stream to fill the entire screen while keeping the aspect ratio, capping of top/bottom... :)

**Comment by cgutman** [comment]
Pinch to zoom in touchscreen mode is implemented since v7.0.0, so I'm going to close this issue. I missed that there was an issue for this or I would have closed it a while ago.

For the full-screen feature, please file a new issue. Also please detail exactly which type of full-screen scaling you would like. It's not clear to me from the discussion here what the exact request is.

- Stretch to fill - Video will be stretched to entirely fill the display (and will distort if the aspect ratio doesn't match the screen). This is what the "Stretch to full screen" checkbox on Android does.
- Stretch to fill with pillarboxing/letterboxing - Video will be stretched (preserving aspect ratio) until one side reaches the maximum size of the screen. This is the default behavior of Moonlight.
- Stretch to fill with cropping - Video will be stretched (preserving aspect ratio) until the video fills the screen. Video content that extends beyond the screen will not be visible.
