### ISSUE TITLE
Permanent Swipe Bar on iPhone X/XS/11 etc.

### ISSUE THREAD

**Issue by readytechgo** [moonlight-stream/moonlight-ios#386]
I play with an Xbox controller hooked up to my iPhone X so I don't use the on screen display. 

When using Photos/Netflix/Watching YouTube etc. the swipe bar at the bottom of the screen disappears after a few seconds however in MoonLight it's permanent.

Is there anyway to cause the swipe bar to disappear after a few seconds as it's not necessary to have a permanent one during gameplay and is a bit distracting to be honest.

**Comment by cgutman** [comment]
Unfortunately there is nothing we can do about this. Apple only allows you to hide the home indicator when the user is not touching the screen. Additionally, if we elect to hide the home bar, that forfeits our system gesture protection, which means just a single accidental swipe from the bottom (even while the home indicator is hidden) will exit the app.

Apple's UI best practices explicitly call out interactive games as cases where one should _not_ hide the home indicator, because it will annoy the user by constantly disappearing and reappearing.

Until Apple provides a way to hide the home indicator without impacting system gesture precedence, this isn't doable.

**Comment by readytechgo** [comment]
Thanks for your reply. 

Perhaps there is a way to add a user selectable option in the iOS Moonlight app to turn off the home indicator - along with an prompt of all of the risks involved when changed?

Alternatively, since iOS 13 now supports controllers only display the option when a controller is detected by iOS?

**Comment by cgutman** [comment]
I've implemented your suggestion. Thanks!

It will hide the home bar as long as the following conditions are true:
- A gamepad is connected
- No on-screen controls are displayed (including partial button layouts for MFi controllers)
