### ISSUE TITLE
Add iPadOS 13.4 Pointer Support

### ISSUE THREAD

**Issue by bgiovand** [moonlight-stream/moonlight-ios#399]
Add mouse / pointer support using the new APIs available in iPadOS 13.4

**Reference:**
https://twitter.com/stroughtonsmith/status/1240851260263354369?s=20
https://developer.apple.com/documentation/uikit/pointer_interactions

**Comment by cgutman** [comment]
I suspect this is still not possible. I looked over the new APIs and none of them seem to allow pointer capture or relative pointer movement.

Simple pointer events that just give the absolute coordinates of the cursor on screen are not sufficient, because the cursor will bump into the edges of the screen (or system UI elements). We need to be able to trap the cursor in our window to receive relative movement deltas.

Android had basic mouse support since Android 2.3, but pointer capture for gaming applications wasn't supported until Android 8.0. I suspect iOS will need to mature in this area too before we have something usable.

**Comment by bgiovand** [comment]
Dang, yep I saw this tweet just after I posted -https://twitter.com/stroughtonsmith/status/1242511225617092611

Confirms exactly what you’ve said.

Here’s hoping there’s a updated APIs in 13.5

**Comment by cgutman** [comment]
I was able to implement absolute mouse motion support using some new parts of the GameStream protocol that I reverse engineered. It won't work in things like FPS games but it works great for remote desktop usage.

**Comment by metherul** [comment]
Sounds fantastic. Would be handy in Civilization.

**Comment by cgutman** [comment]
Released in Moonlight iOS v5.0.0.

**Comment by susemeee** [comment]
I've been using this feature and found that simultaneous LMB/RMB click event does not work. Everything except this (and relative mouse capturing) works great.

I don't know right now whether this is a hardware issue, or limitation of iOS API, or just a bug. I'm going to support further investigation if needed.

**Comment by slrgt** [comment]
i cant seem to control the mouse of the host im controlling with moonlight. im using an ipad with a bluetooth mouse
