### ISSUE TITLE
Third-party Bluetooth mouse input not working with Magic Keyboard attached

### ISSUE THREAD

**Issue by dannystewart** [moonlight-stream/moonlight-ios#422]
Third-party Bluetooth mice don’t work in a Moonlight stream when the Magic Keyboard is attached. I’ve tried two Bluetooth mice, and they work fine across the system, but as soon as I start streaming via Moonlight, they go dead. Pop the iPad off the Magic Keyboard, and input works normally. Pop it back on, it goes dead again. The mouse continues to work throughout the rest of iPadOS the whole time, even in Moonlight—it’s only when streaming with the Magic Keyboard connected that mouse input to the host stops working. The built-in trackpad still works, and it seems the Magic Mouse will continue to work whereas third-party mice will not.

**Comment by cgutman** [comment]
This is because iOS 14.0 doesn't expose all third-party mice via the new GCMouse API, even when they work with the older iOS 13 UIKit API. And worse, to use the GCMouse API we need to lock the mouse cursor, which breaks any mice using the older UIKit API.

To best deal with that mess, we opportunistically switch between GCMouse (relative mode) and UIKit (absolute mode) pointer control. When you connect a GCMouse compatible mouse (like your Magic Keyboard includes), Moonlight switches to GCMouse mode and locks the cursor, rendering the other third party mice that don't work with GCMouse inoperable.

It seems based on our testing (myself and several folks on Discord), that Apple's GCMouse support seems better for USB-connected mice (either via USB-C or Lightning to USB adapters) than Bluetooth mice for some reason (probably just a bug).

Apple needs to fix the GCMouse API to work with all mice supported by the UIKit API. I know at least one user has filed a feedback request with Apple to that effect.

**Comment by dannystewart** [comment]
Thanks for the in-depth response. I suspected it might be an iPadOS bug rather than a Moonlight bug but just wanted to be sure. I will file feedback with Apple on this as well.

**Comment by cgutman** [comment]
Can you confirm this still happens on iOS 14.2?

**Comment by dannystewart** [comment]
Based on some quick testing after updating to iOS 14.2, this does not appear to be a problem anymore!

**Comment by cgutman** [comment]
Cool, that matches my testing too. Closing this as fixed in iOS 14.2.
