### ISSUE TITLE
Moonlight and GeForce Experience games list don’t match

### ISSUE THREAD

**Issue by jonstump** [moonlight-stream/moonlight-ios#430]
My game list between Moonlight and GeForce Experience do not match. 

While there are overlap in the games between the two lists, they aren’t the same. Some games show up in Moonlight, but not GeForce Experience, for example Fez. Others are the opposite as they show up as a GeForce Experience game, but not in moonlight like Catherine. So far I can find nothing that says these shouldn’t match. I’ve updated GeForce, reinstalled moonlight on my iPhone and repaired two two, and I’ve also rebooted my computer several times to no avail.

Here’s a couple photos showing the differences if it’s helpful:
![97527627-E065-418F-9741-0472A71B6CB3](https://user-images.githubusercontent.com/59323850/99843967-3fdb7d00-2b27-11eb-906f-e1a18cc5f05c.png)
![320D7D0D-E415-4699-8625-AA369A60489E](https://user-images.githubusercontent.com/59323850/99843974-44079a80-2b27-11eb-99e6-1c58ba591cdc.jpeg)

How do I get Moonlight to pull the games that are actually in my list of games according to the GeForce Experience app?

**Comment by cgutman** [comment]
This is by design. GFE only report games that Nvidia has validating for GameStream compatibility to GameStream clients, but it will show any game in the UI.

You can add any game you want manually - https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#adding-custom-programs-that-are-not-automatically-found

**Comment by jonstump** [comment]
The instructions seem to be for games not found by GFE. For example Control is and doesn’t appear in Moonlight. So I guess I’m confused as to why a game already found would need to be added again?

**Comment by cgutman** [comment]
The Shield streaming game list and GFE game lists are not the same. As I said before, only games that are validated by Nvidia specifically for GameStream compatibility will appear in GameStream clients by default. Control is not one of those validated games, thus you must add it manually to the Shield streaming game list.

**Comment by jonstump** [comment]
Is there a different list they have for this than their website? Because I keep seeing Control under their list of games. Every source I look at points me to this list for their approved streaming games. Do you have another I can look at that’s accurate is this one isn’t?

 https://www.nvidia.com/en-us/geforce-now/games/

**Comment by cgutman** [comment]
Not anymore, the online list was removed by Nvidia - https://www.nvidia.com/en-us/geforce/forums/gamestream/19/242271/what-happened-to-the-list-of-supported-gamestream-/

GeForce Now supported games are different. But it doesn't really matter what is officially supported or not, since you can just add whatever game you want to the list following the instructions I provided in the initial response.
