### ISSUE TITLE
got a pairing failed

### ISSUE THREAD

**Issue by Xchkoo** [moonlight-stream/moonlight-ios#451]
it's ok when i enter the pairing passwd, then it shows a waring:
Pairing Failed
An SSL error has occurred and a secure connection to the server cannot be made.
my device running ipados 14.4

**Comment by cgutman** [comment]
This is typically caused by anti-malware software on your host PC or hardware on your network that performs interception of SSL traffic. While other applications may tolerate this, Moonlight is strict about only allowing connections to a PC if we can guarantee that the connection is secure. You may try pairing on a different network. If that fails, reinstalling the latest version GeForce Experience may also resolve it.
