### ISSUE TITLE
Pinch to zoom in trackpad mode

### ISSUE THREAD

**Issue by beren12** [moonlight-stream/moonlight-ios#455]
Please give us an option to enable pinch to zoom with trackpad mode not just with touch. I find trackpad mode is far better for me most of the time, but the inability to zoom the screen when needed is a big limit. I know there's the accessibility option but that's not as good as the built in enlarge. It's already in the app just remove the limit please.

**Comment by cgutman** [comment]
It’s not an arbitrary limit. Zoom is not supported in touchpad mode because the pan and scroll gestures would collide.

The 2 finger scroll gesture is the same gesture as the 2 finger up-down pan.

**Comment by beren12** [comment]
> On Apr 14, 2021, at 10:51 AM, Cameron Gutman ***@***.***> wrote:
> 
> 
> It’s not an arbitrary limit. Zoom is not supported in touchpad mode because the pan and scroll gestures would collide.
> 
> The 2 finger scroll gesture is the same gesture as the 2 finger up-down pan.

Ah but pinch is not the same as scroll/pan. Other clients manage to have zoom in trackpad mode, iirc microsoft RD client, Remoter, VNC Viewer as well as scroll.

**Comment by cgutman** [comment]
It’s not the pinch. It’s the pan gesture you need to move around when zoomed.

We can’t know the position of the cursor in touchpad mode, so we can’t just pan when the cursor reaches the edge of the screen as other apps (like Chrome Remote Desktop) do.

**Comment by beren12** [comment]
So RealVNC and Remoter both support this. With RealVNC when you zoom in the mouse in the center of the screen unless you are up against the edge of the remote monitor then the mouse can move all the way to the edge. With this way, if you know the coords of your view you know the mouse position.

**Comment by cgutman** [comment]
The difference is that they know the position of the host mouse cursor. We do not. We couldn't pan the screen to follow the cursor, because we don't know where the cursor is.

When we are operating in trackpad mode, the mouse is in relative mode. This means we're only sending mouse motion deltas (ex: move mouse 5 points to the left and 10 points up) rather than absolute coordinates (ex: move the mouse to position (1833, 788) on screen). This ensures compatibility with games which use relative mouse input or cursor locking to operate the camera and similar things.

We could add yet another mode of mouse input, but I don't think the user experience would be very good. We'd have to somehow explain the difference between:
- Trackpad mode with broken panning, but it works for camera control in games (what we have now)
- Trackpad mode where panning works, but camera flies around out of control in games (what we would need to support this feature)

Since Moonlight is a primarily gaming-focused piece of software, I think relative mouse input in trackpad mode is the right tradeoff. Users that want to navigate the desktop or play games like Civ can use touchscreen mode to be able to pan, zoom, and directly click UI controls.

**Comment by bmscmoreira** [comment]
Maybe Im doing something wrong but I cant pinch zoom in trackpad or in mouse mode. Im using Moonlight latest version on an Android phone. Can someone point me to a solution?

**Comment by stef1949** [comment]
This would be useful. I use moonlight for VFX workflows requiring GPU acceleration (Blender & EmberGen)
