### ISSUE TITLE
Open-Stream tvOS handshake error -4

### ISSUE THREAD

**Issue by ScarAce1989** [moonlight-stream/moonlight-ios#458]
I use Open-Stream to use Moonlight with my AMD GPU. I can connect with my iPhones and MacBook Pro, but I get an error trying to connect to my Apple TV. I tried it over LAN and WiFi, no luck.

Open-Stream > Moonlight Apple TV - handshake failed -4

Open stream:
info: CLIENT CONNECTED TO RTSP
info: CLIENT DISCONNECTED FROM RTSP

Apple TV:
Connection failed
RTSP handshake failed with error -4
Check your firewall and port forwarding rules for port(s): TCP 48010 UDP 48000 UDP 48010

**Comment by cgutman** [comment]
I suspect the reason is that Moonlight is requesting 7.1 surround sound and OpenStream doesn't send the opus mappings for it. The relevant code in moonlight-common-c is here: https://github.com/moonlight-stream/moonlight-common-c/blob/65047ac0e21450aa2064eee74b1a0f509cc189ad/src/RtspConnection.c#L584-L607

The bug is in OpenStream here, not Moonlight. I recommend filing an issue there: https://github.com/LS3solutions/openstream-server
