### ISSUE TITLE
Can't disable hevc codec in tvOS15

### ISSUE THREAD

**Issue by 020794** [moonlight-stream/moonlight-ios#481]
"Use HEVC Codec" option was disabled, but the statistic info still showed the codec was HEVC and the GPU(gtx 980ti which does not support hevc hw encoding) usage was about 20% high.

**Comment by cgutman** [comment]
This is intended behavior. With reference frame invalidation disabled for H.264 as it currently is, there is no reason to ever pick H.264 over HEVC if HEVC is available on client and server. Moonlight will automatically choose HEVC when client and server support it.

The GTX 980 Ti [does have HEVC encoding](https://en.wikipedia.org/wiki/Nvidia_NVENC#Third_generation,_Maxwell_GM20x). It doesn't have HEVC _decoding_, but that's not relevant for hosting.

**Comment by euroclydon37** [comment]
I'm not an expert in codecs by any means, but everything I've read says that the HEVC codec introduces more latency than the H264 codec because of compression complexity. I read somewhere that the Shield TV uses H264 for this reason, and I definitely do get better input latency with that client vs the Apple TV (measured with timestamped slow motion video recordings), so I was hoping to disable the setting to test it.

Is there any way I could convince you to re-enable the setting option? lol

**Comment by brunosmarques** [comment]
I don't know if HEVC performs better or not, but I do think the app should honor the config. I feel it's a very strange thing to let the user select the preferred codec but overriding anyway. 

You can go with three options, "Auto", "HEVC" and "H264", or just "Auto" and "H264", but please do not ignore my choice.

**Comment by cgutman** [comment]
> I'm not an expert in codecs by any means, but everything I've read says that the HEVC codec introduces more latency than the H264 codec because of compression complexity.

This is not correct generally. You're probably reading about CPU decoding where the performance difference can be notable. In fixed function decoding/encoding hardware, you are unlikely to see perceptible differences.

Even when equivalent, HEVC is still a better selection because it reduces the bandwidth for equivalent image quality. Less bandwidth means less time spent waiting for network transmission, less chance of packet loss causing frame drops, and less network load (latency can increase with load due to bufferbloat).

> I read somewhere that the Shield TV uses H264 for this reason

Shield TV always uses HEVC if available, like Moonlight's current behavior on tvOS.

> I definitely do get better input latency with that client vs the Apple TV (measured with timestamped slow motion video recordings), so I was hoping to disable the setting to test it.

There's a lot more to click-to-photon latency than just the codec. Shield TV has fast paths for input to avoid latency and prefers performance over power consumption when configuring the decoder clocks. It also supports HDMI 2.1 ALLM to ensure low latency output on capable TVs.

> I don't know if HEVC performs better or not, but I do think the app should honor the config. It's a very strange thing to let the user select the preferred codec but overriding anyway.

Disabling the option was a workaround for a tvOS bug. The commit message has more details: https://github.com/moonlight-stream/moonlight-ios/commit/2d8d17616008b7c75a6ba552997d0caa6f6187f9

It was intended to be temporary, though it has lasted longer than I had hoped. I will retest on tvOS 15 and see if reference frame invalidation can be safely re-enabled. I will also re-enable the HEVC option and have it default to enabled.

> You can go with three options, "Auto", "HEVC" and "H264", or just "Auto" and "H264", but please do not ignore my choice.

To be clear, the codec options you're referring to are part of the iOS client and those option work as expected. The tvOS client has a simple On/Off toggle for requesting HEVC video rather than a list of named options.

**Comment by euroclydon37** [comment]
@cgutman That makes a lot of sense and confirms my testing from earlier today. I pulled this repo and hard coded `_streamConfig.supportsHevc` to false to force h264 and saw no performance difference.

Thanks for the thorough explanation!
