### ISSUE TITLE
DS5 支持

### ISSUE THREAD

**Issue by Sskra** [moonlight-stream/moonlight-ios#483]
1.希望串流后，PC能够将DS5识别为DS5手柄，而不是XBOX 360！  
2.完成第一点后，希望能够支持DS5触控板，陀螺仪！

**Comment by don17sch** [comment]
I am going to leave a translation here.
provided by Google Translate

1. Hope that after streaming, PC can recognize DS5 as DS5 controller instead of XBOX 360!
2. After completing the first point, I hope to support DS5 trackpad and gyroscope!

**Comment by don17sch** [comment]
Now to leave a comment on this. I think that you cannot natively do this due to Nvidia Shield only supporting xinput. but you can use a tool like described here 

https://factschronicle.com/how-to-use-an-xbox-one-or-360-controller-on-ps4-remote-play-22514.html

this will allow you to take the xinput that your windows pc recieves and convert it back to a dual shock controller. 
I do not know how well this would work with a dual sense controller but I doubt that the track pad or the gyroscope will work correctly

**Comment by Sskra** [comment]
> Now to leave a comment on this. I think that you cannot natively do this due to Nvidia Shield only supporting xinput. but you can use a tool like described here 
> 
> 
> 
> https://factschronicle.com/how-to-use-an-xbox-one-or-360-controller-on-ps4-remote-play-22514.html
> 
> 
> 
> this will allow you to take the xinput that your windows pc recieves and convert it back to a dual shock controller. 
> 
> I do not know how well this would work with a dual sense controller but I doubt that the track pad or the gyroscope will work correctly

谢谢，我回去试一下，如果不行，那只能等待英伟达支持DS5了。

**Comment by Sskra** [comment]
> Now to leave a comment on this. I think that you cannot natively do this due to Nvidia Shield only supporting xinput. but you can use a tool like described here 
> 
> 
> 
> https://factschronicle.com/how-to-use-an-xbox-one-or-360-controller-on-ps4-remote-play-22514.html
> 
> 
> 
> this will allow you to take the xinput that your windows pc recieves and convert it back to a dual shock controller. 
> 
> I do not know how well this would work with a dual sense controller but I doubt that the track pad or the gyroscope will work correctly



谢谢，上面网址的内容不是我需要的需求，现在只能等待英伟达支持DS5输入。

**Comment by Sskra** [comment]
我找到解决办法了，我用reWASD将XBOX360模拟成PS4手柄了，进去游戏后就可以使用DS手柄样式了！由于XBOX360不支持陀螺仪和触控板，这个功能在串流上暂时无法解决了！  请问一下，moonlight串流支持几个手柄玩家同时使用呢？

**Comment by don17sch** [comment]
leaving translations provided by google translate

Thank you, the content of the above URL is not what I need, and now I can only wait for NVIDIA to support DS5 input.


I found a solution. I used reWASD to simulate the XBOX360 as a PS4 controller. After entering the game, I can use the DS controller style! Since XBOX360 does not support gyroscope and touchpad, this function cannot be solved temporarily on streaming! Excuse me, does moonlight streaming support multiple gamepad players using it at the same time?

**Comment by don17sch** [comment]
does anyone here know if moonlight supports multiple controllers or if it only supports a single controller?

**Comment by cgutman** [comment]
Moonlight supports up to 4 controllers.

It looks like you've found a workaround (and this is a GameStream limitation, rather than a Moonlight bug), so I'm going to close it.

As an aside, [Sunshine](https://github.com/SunshineStream/Sunshine) supports a setting to emulate either an Xbox 360 controller or a PS4 controller.

**Comment by oxkenshin** [comment]
DS5 works good on android moonlight. It seems only a iOS version issue.
