### ISSUE TITLE
Match the aspect ratio of iPad screen.

### ISSUE THREAD

**Issue by KrisCris** [moonlight-stream/moonlight-ios#492]
**Is your feature request related to a problem? Please describe.**

I hope it can automatically change the resolution to what match the aspect ratio of my end device when stream from my computer.

**Describe the solution you'd like**

Change the screen resolution during connection.

**Additional context**
I once used Microsoft’s Remote Desktop client, who would automatically resize the screen to match my device, which is very nice.

**Comment by cryptofyre** [comment]
+1 on this. Playing with a 1920x1080 black barred screen is kind of a drag.

**Comment by cgutman** [comment]
Custom resolutions are already implemented in v8.0.0 which is pending Apple review.

**Comment by cryptofyre** [comment]
Awesome! Great work.

**Comment by salimcherifi** [comment]
Any news on the review ?

**Comment by jzjz2000** [comment]
Status update? I'm looking forward to custom resolutions for the M1 iPad Pro.
Thanks

**Comment by cgutman** [comment]
Still in review.

I filed a Developer Support ticket about the delay, but they simply said they needed more time to review it.

We just have to wait until they approve or reject it. Until then, we can’t do anything.

**Comment by jzjz2000** [comment]
Released Sunday nite in US App Store.
Finally, not more black bars.
Runs well on M1 iPad Pro.

Thanks for the hard work😀

**Comment by salimcherifi** [comment]
I don't understand how it works ? if I set a custom resolution the desktop appears very stretched out ?

**Comment by cgutman** [comment]
Finally approved and released in v8.0.0

**Comment by georaldc** [comment]
I'm aware that this was closed due to custom resolution support being added to v8, but I just wanted to ask: did this latest update change the way things were being streamed to a device? For a long time, I've always defaulted to the 4k resolution option for my iphone 12 pro, which gives me proper black bars. If I switch to a 21:9 resolution mid-stream, the stream's aspect ratio adjusts properly (nearly filling up the screen of my phone). This allowed me to use either a 16:9 or 21:9 resolution when needed. It's been a while since I've streamed to my phone, but after trying it again recently, selecting 4k now locks me to a 16:9 container always. The aspect ratio never changes when I select something like 3440x1440 in a game (leading to a stretched image to fit within a 16:9 container).

I guess I can use the custom resolution option now but I think due to it being unsupported by gamestream, I get a 21:9 stream running in 720p in some cases

**Comment by georaldc** [comment]
Anything custom in Moonlight makes the stream fallback to 1280x720. My computer monitor is a 21:9/3440x1440 monitor so there is no need for a custom resolution. I think some games that run in exclusive fullscreen work fine when ingame resolutions are adjusted back to 3440x1440, but when I start streaming from my desktop and launch other applications (say emulators), they stay stuck in 1280x720 stretched to a 21:9 container.
