### ISSUE TITLE
Can't pair to a host with a different port family

### ISSUE THREAD

**Issue by MAVREE** [moonlight-stream/moonlight-ios#529]
**Device details (please complete the following information)**
 - iOS/tvOS version: iOS 16.0
 - Device model: iPhone 12 Pro
 - App version: 8.2.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 21H2
 - Using Sunshine instead of GFE to change ports in use

**Additional context**
I need to use a different family port on a secondary PC as the main one already uses the default ports, so I just lowered the main port to 27989 (so all the ports are 27984 - 27989 - 28010 - 27998 - 27999 - 28000 - 28010).
This works with moonlight-qt (on Windows) as it even discovers the device automatically, but just in case I tried to add it manually (1.2.3.4:27989) and it pairs.
The iOS app instead cannot find the device and adding the host ip manually just throws a "could not connect to host" error.

**Comment by ericsyj** [comment]
Same issue.

**Comment by austinarchibald** [comment]
Can you pair with a sunshine host on a custom port now? I installed sunshine on macOS and want it under a different port since I also use sunshine on my PC. Tried to pair on macOS app and Vision Pro app, but both say not authorized. It will only pair when it's on the default port. Not sure if this is Moonlight related or sunshine on macOS related...
