### ISSUE TITLE
[Feature Request] Click and Drag 

### ISSUE THREAD

**Issue by henrylai** [moonlight-stream/moonlight-ios#72]
Currently there does not seem to be any click and drag functionality. Many games use this and I think it  is a very basic core function that needs to be implemented.

**Comment by krunkster** [comment]
I started working on implementing a "touchscreen" mode emulation that maps a press on the touch screen to the host screen, and then a release when you let up.  As a proof of concept I got it to a working state but I'm running into some pretty severe knowledge gaps though because I don't understand how to get the actual host resolution instead of the stream resolution, so I can't accurately scale the mouse movement yet.

**Comment by cgutman** [comment]
This was added a while back
